# Generated by Django 4.0.6 on 2022-08-09 00:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personne',
            options={'ordering': ('-date_joined',)},
        ),
        migrations.AlterModelManagers(
            name='personne',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='personne',
            name='date_enregistrement',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='personne',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='personne',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personne',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personne',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
